name: CICD

on:
  push:
    branches:
      - main
  workflow_dispatch: # GitHub Actions の UI から手動で実行するためのトリガー

jobs:
  build:
    runs-on: ubuntu-latest # ジョブを実行するランナーの環境を指定
    env :
      VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
      VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
    steps:
      - name: Checkout repository  # ワークフローのジョブ内でリポジトリのコードを取得し、ビルド、テスト、デプロイなどの操作ができる
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Remove node_modules and package-lock.json
        run: rm -rf node_modules package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Run Prettier
        run: npx prettier --write .
      - name: Run tests
        run: npm run test # 環境変数は定義済み
      - name: Build project
        run: npm run build
      # アーティファクト(ソフトウェア開発プロセスにおいて生成される成果物)をアップロード
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts # アップロードするアーティファクトの名前を指定
          path: dist # distディレクトリ内のすべてのファイルがアーティファクトとしてアップロードされる

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts # buildでアップロードしたアーティファクトの名前
          path: dist
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: "${{ secrets.FIREBASE_PROJECT_ID }}"
          channelId: live
